name: Release 

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs: 
        version: ${{ steps.sementic_release.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # See https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html
      - name: Semantic Release
        id: sementic_release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        run: |
            echo ${{ needs.release.version }}
